SAMPLE_RATE = 16000
CHUNK_SIZE = 256
CHANNELS = 1
DTYPE = "int16"

AUDIO_QUEUE_SIZE = 128

PRE_ROLL_MS = 500
PRE_ROLL_CHUNKS = 32

CANDIDATE_END_SILENCE_CHUNKS = 32

MAX_CANDIDATE_SECONDS = 15
MAX_CANDIDATE_SAMPLES = SAMPLE_RATE * MAX_CANDIDATE_SECONDS

PHONETIC_MODEL = "facebook/wav2vec2-xlsr-53-espeak-cv-ft"
PHONETIC_QUEUE_SIZE = 4

EVIDENCE_ACCEPT_SCORE = 7
EVIDENCE_REJECT_SCORE = 2

EVIDENCE_MIN_DIVERSITY = 0.60
EVIDENCE_MIN_ACTIVE_NON_BLANK = 0.15
EVIDENCE_MIN_PHONETIC_CONFIDENCE = 0.55

ARTICULATION_FRAME_MS = 25
ARTICULATION_HOP_MS = 10
ARTICULATION_MIN_FREQ = 80
ARTICULATION_MAX_FREQ = 7600
ARTICULATION_ACTIVE_RATIO = 0.15

AST_MIN_GROUP_SCORE = 0.25
AST_MIN_MARGIN = 0.15

CALIBRATION_WINDOW_SECONDS = 4
CALIBRATION_WINDOW_CHUNKS = int(
    CALIBRATION_WINDOW_SECONDS
    * SAMPLE_RATE
    / CHUNK_SIZE
)

CTC_ACCEPT_MIN_CONFIDENCE = 0.35